### ISSUE TITLE
Input subscription undefined when date picker component is used in a dynamic component.

### ISSUE THREAD

**Issue by priaChandrasekhar** [DanielYKPan/date-time-picker#263] opened 2018-02-05 20:30 UTC
I am creating a dynamic component when i open a dialog. This component contains a datetime picker. On close of this dialog, the input subscription is undefined and errors on ngDestroy. Is there a fix for this? If not, I have a PR ready.

**Comment by DanielYKPan** [comment] 2018-02-05 20:47
I tried it in a dynamic component, but didn't have the error you described.
Could you provide more inform or a demo to the issue you described?

**Comment by priaChandrasekhar** [comment] 2018-02-05 22:08
core.js:1440 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'unsubscribe' of undefined
TypeError: Cannot read property 'unsubscribe' of undefined
    at OwlDateTimeComponent.ngOnDestroy (date-time-picker.component.js:187) 

OwlDateTimeComponent.prototype.ngOnDestroy = function () {
        this.clean();
        _**this.dtInputSub.unsubscribe();**_
        this.disabledChange.complete();
        if (this.popupRef) {
            this.popupRef.dispose();
        }
    };

The above highlighted line is causing the error.  
On click of a button, i open a dialog. It contains a dynamic component which includes a form with the datetime picker and other fields in its template. I set the date and other form fields, and submit. On submit of this form, I close this dialog and open another dialog. When i close the second dialog, the ui hangs with the above mentioned console error.

**Comment by DanielYKPan** [comment] 2018-02-05 22:43
Do you have the picker in the second dialog?
For what I understand, the first dialog has the picker, and when you submit, you close the first dialog (which has the picker).

And the error exists mostly because you have a picker, but that picker doesn't not have a relatively input.

**Comment by priaChandrasekhar** [comment] 2018-02-05 22:47
Yes you are correct. The picker is only in the first dialog. the second dialog is just like an alert with an OK button. I get this error even if i do not submit the form and instead i just cancel and close the first dialog.

**Comment by DanielYKPan** [comment] 2018-02-05 22:50
The error exists because you have a picker, but that picker doesn't have a associated input.

**Comment by priaChandrasekhar** [comment] 2018-02-05 23:03
The first dialog has the picker associated with an input. the second dialog is just an alert. I m not sure why the close of the second dialog should throw this error. I have no workaround this.  :(

**Comment by DanielYKPan** [comment] 2018-02-05 23:09
As I said before, the error exists because you had a picker which did not have an associated input, you might have to debug yourself. This is not a bug from the picker.
I would close this for now.

**Closed by DanielYKPan** 2018-02-05 23:09 UTC
