### ISSUE TITLE
ISO date not working

### ISSUE THREAD

**Issue by Frank-Fichte** [DanielYKPan/date-time-picker#192] opened 2017-11-13 14:00 UTC
The current version (beta12) not working with iso dates something like  2017-11-13T13:34:10Z
In the previous version it's working.

<owl-date-time inputId="tar-vondatum" dataType="date" [(ngModel)]="test.date" dateFormat="DD.MM.YYYY" type="calendar"></owl-date-time>

this.test = {
            'date': '2017-11-13T13:34:10Z'
        };

**Comment by MaikelS11** [comment] 2017-11-25 08:55
What isn't working? When I create a variable with the value "2017-11-13T13:34:10Z" and put it in the ngModel, the calendar shows the date/time in my localtime (2017-11-13T14:34:10)

**Comment by ejahn** [comment] 2017-12-03 17:37
I can confirm that. For me, it's not possible to set dates from an iso date, since updating from 5.0.0-beta.12. 

The calendar does not show a date. It can only be set after clicking on a day multiple times. After that, setting hours or minutes breaks it again.

**Comment by DanielYKPan** [comment] 2017-12-03 21:36
@Frank-Fichte @MaikelS11 @ejahn 
The reason why iso not working is because the [dateFormat] is not right.
By default, the [dateFormat] is 'YYYY/MM/DD HH:mm'.

**Comment by DanielYKPan** [comment] 2017-12-03 22:15
Update to 5.0.0-beta.15
It should be fixed.

I would close this for now.

**Closed by DanielYKPan** 2017-12-03 22:15 UTC
Labels: bug
