### ISSUE TITLE
reseting time when setting a new date

### ISSUE THREAD

**Issue by pos-isalem** [DanielYKPan/date-time-picker#196] opened 2017-11-22 08:51 UTC
Kindly when choosing **range** date time picker, the following issue happened to me:

Changing on date will reset the time that was selected before to 12:00, and it should be the same, since I changed the date not the time.

Steps to duplicate: 

1- create range mode date & time picker.
2- set the default date & time value.
3- click on a new date, the time will reset to 12:00 || 00:00.
4-  change on time.
5- click on other date and the last selected time will reset again.

The issue are only duplicated with me only on **_range_** mode date time picker.

Regards
Ihab Salem

**Comment by mstawick** [comment] 2018-01-22 14:58
Same thing happens with single picker, using OwlMomentDateTimeModule and reactive forms

**Comment by clarketus** [comment] 2018-01-30 22:54
I came across this issue too, using OwlMomentDateTimeModule along with reactive forms, same as @mstawick . 

I managed to fix the issue by creating my own adapter. The issue is in the ng-pick-datetime-moment package, of which the source code is not in this github repo... or anywhere else I could find on google.

I opened the npm package in my node_modules directory, and in the file moment-adapter/moment-date-time-adapter.class.js on line 140 is where a new moment object is constructed:

`var result = moment({ year: year, month: month, date: date }).locale(this.locale);`

This is missing the hours minutes and seconds values. I fixed by changing it to:

`var result = moment({ year: year, month: month, date: date, hours: hours, minutes: minutes, seconds: seconds }).locale(this.locale);`

It was a bit of a pain having to copy out the adapter from the npm package and convert to typescript, but in the end I managed to get the bug solved.

@DanielYKPan can you make the source for ng-pick-datetime-moment available on github?

Thanks!

**Comment by DanielYKPan** [comment] 2018-01-31 10:47
Update the ng-pick-datetime-moment package to latest version and the issue should be fixed.
Thanks, guys.

**Closed by DanielYKPan** 2018-01-31 10:47 UTC
