### ISSUE TITLE
After set the locale, year change not detected when change the year manually(without pick the year)

### ISSUE THREAD

**Issue by rameshyala** [DanielYKPan/date-time-picker#341] opened 2018-04-27 07:17 UTC
Hi, when i am change the year in by manually(with keyboard) enter the year this not hit the below pickdate() function, first it was works fine, i am adding the locale to this 'en-IN' after this was not working. Below i am share my code.
Please help me where i do the mistake

     @Component({
          selector: 'sb-clr-date-picker',
          template: `<input
               [formControl]="control"
               (dateTimeChange)="pickDate($event)"
               [owlDateTimeTrigger]="dtPicker2"
              [owlDateTime]="dtPicker2">
              <owl-date-time [pickerType]="'calendar'" #dtPicker2></owl-date-time>`
      })

    export class SbClrDatePickerComponent {
       @Input() control: FormControl = new FormControl(new Date());
       @Output() change = new EventEmitter();

      constructor(dateTimeAdapter: DateTimeAdapter<any>) {
          dateTimeAdapter.setLocale('en-IN');
      }

      pickDate(d: Date) {
         this.change.emit(d);
      }
    }

**Comment by DanielYKPan** [comment] 2018-04-28 00:16
Pleas use [StackBlitz](https://stackblitz.com/) to build an app and show the issue you mention about
I would close this until it is confirmed as an issue.

To answer you question, the date time format might change after you setting a different locale and the picker could not translate your date time string to a proper Date object. In this case, the picker would not fire a (dateTimeChange) event.

**Closed by DanielYKPan** 2018-04-28 00:16 UTC

**Comment by rameshyala** [comment] 2018-04-30 05:39
Hear is the  [Stack blitz](https://stackblitz.com/edit/angular-7faqjv), in this you test select today date after change the year into 2019(or something) by manually by keyboard then open date picker it still showing the today, i am using form control to this it will give null in this case.

**Comment by DanielYKPan** [comment] 2018-04-30 06:40
As I said before, the date time format might be changed after you setting a different locale and the picker could not translate your date time string to a proper Date object.

Back to your example,
this is because the locale en-In date time format is 'dd/mm/yyyy', but Native Javascript Date object could not parse the string to a specific format. This is nothing we could do. Native Javascript Date parse() function would always parse a string to Date object relative to your system's locale. In this case, I would recommend you to use `OwlMomentDateTimeModule` and let MomentJs to handle locale parse and format. You could learn more about `OwlMomentDateTimeModule` from the README and the demo page.
