### ISSUE TITLE
ERROR TypeError: _this._driver.validateStyleProperty is not a function

### ISSUE THREAD

**Issue by tiagomsmagalhaes** [DanielYKPan/date-time-picker#454] opened 2018-08-16 13:39 UTC
I installed latest version and I'm getting this error when clicking on input.

I'm running angular 6 on a Meteor Application and I fetch successfully the css file and tried with both BrowserAnimationsModule and NoopAnimationsModule

**Comment by DanielYKPan** [comment] 2018-08-16 20:12
Please use [StackBlitz](https://stackblitz.com/) to build an app and show the issue you mention about
I would close this until it is confirmed as an issue.

**Closed by DanielYKPan** 2018-08-16 20:12 UTC

**Comment by donp-kitcheck** [comment] 2019-08-20 18:09
@DanielYKPan 

I'm getting this same issue immediately after installing the component.
You now have three confirmed reports of the same issue from three separate developers.

Your demo pages are built in a way that's not representative of an Angular 5+ app, so you may want to try following the installation steps on your own README to set up and use the component, to see if you run into this same issue.

For now, the component is unusable for me, as it seems to be for the other two reporters of this issue.
