### ISSUE TITLE
Hovering over dates issue in IE11

### ISSUE THREAD

**Issue by ankitw77** [DanielYKPan/date-time-picker#70] opened 2017-06-21 07:17 UTC
In IE 11 when hovering over a date and moving on to a next date leaves the highlighting background colour/ style on previous hovered dates. On inspecting the element, the highlighting style was to be an inline style that was handled via Angular and somehow it seems to be not working correctly in IE11. IMHO I think it would be better to handle that via CSS. For the moment I handle it by overriding the class in CSS as: 

.picker-day.picker-show:not(.picker-day-selected) {
  background-color: white !important;

  &:hover {
    background-color: rgb(179,212, 234) !important;;
  }

}

![dates_selected](https://user-images.githubusercontent.com/7385267/27371782-bf1a441e-567f-11e7-8934-6da13b6bd2dc.jpg)

**Comment by DanielYKPan** [comment] 2017-06-23 11:23
@ankitw77 
Have you tried it in other browsers?

**Comment by harikrishnan-u01** [comment] 2017-07-05 14:24
The demo (https://danielykpan.github.io/date-time-picker/) itself has this issue in IE11. Otherwise this widget looks cool. The problem is that most users for my application will be using IE11 and above.

The dropdown example also has other style issues in IE11. Kindly check "Today" and "Cancel" overlapping with the dates:

![image](https://user-images.githubusercontent.com/10159959/27868790-d7562f4c-616b-11e7-8881-0e3565fc586e.png)

@DanielYKPan : Will there be any fix for this in next release?

Thanks,
Hari

**Comment by weglarzdamian** [comment] 2017-07-05 16:05
I have same problem, and similar to @harikrishnan-u01, we have requirement to use IE11 for our application. 
@DanielYKPan, what is the plan for fixing this issue?

**Comment by DanielYKPan** [comment] 2017-07-06 04:16
@ankitw77 @harikrishnan-u01 @weglarzdamian 
Update to latest picker version. It should be fixed.

**Closed by DanielYKPan** 2017-07-06 04:16 UTC
