### ISSUE TITLE
'min' property of datetimepicker is not working property

### ISSUE THREAD

**Issue by v2amruta** [DanielYKPan/date-time-picker#342] opened 2018-04-27 07:56 UTC
I have set the min property of datetimepicker in a .ts file as following

min = new Date(1900, 0, 1);

When i select the year less than 1900 then it redirected me to 1899 year-view instead of 1900 year-view. It is working as expected for 'max' property.

Question : When we are setting max and min date then why we are allowing user to select any other date which is not in max-min date range???

**Comment by DanielYKPan** [comment] 2018-04-28 00:07
I could not reproduce the issue you described.
Pleas use [StackBlitz](https://stackblitz.com/) to build an app and show the issue you mention about
I would close this until it is confirmed as an issue.

Answer to your question: No, you could not select any date out of your max-min range.

**Closed by DanielYKPan** 2018-04-28 00:07 UTC
