### ISSUE TITLE
ERROR: Attempting to attach an unknown Portal type

### ISSUE THREAD

**Issue by tomschreck** [DanielYKPan/date-time-picker#276] opened 2018-02-20 17:01 UTC
Hello.  I'm getting the following error when deploying my app to our dev environment.  Date-Time-Picker works as expected in our local environment.  I've copied examples from your demo page and still get this error.  Here's code I'm using from your demo page producing this error:

`						Date Time:
						<input [owlDateTime]="dt1">
						<span class="trigger" [owlDateTimeTrigger]="dt1">
							<i class="fa fa-calendar"></i>
						</span>
						<owl-date-time #dt1></owl-date-time>	
`

I'm using  the following packages:

		"@angular/animations": "^5.0.0",
		"@angular/cdk": "^5.2.1",
		"@angular/common": "^5.0.0",
		"@angular/compiler": "^5.0.0",
		"@angular/core": "^5.0.0",
		"@angular/forms": "^5.0.0",
		"@angular/http": "^5.0.0",
		"@angular/platform-browser": "^5.0.0",
		"@angular/platform-browser-dynamic": "^5.0.0",
		"@angular/router": "^5.0.0",
		"angular2-moment": "^1.7.0",
		"angular2-multiselect-dropdown": "^2.3.0",
		"ng-pick-datetime": "^5.1.5",
		"ng-pick-datetime-moment": "^1.0.4",

ERROR Error: Attempting to attach an unknown Portal type. BasePortalOutlet accepts either a ComponentPortal or a TemplatePortal.
    at throwUnknownPortalTypeError (portal.es5.js:47)
    at DomPortalOutlet.webpackJsonp.../../../cdk/esm5/portal.es5.js.BasePortalOutlet.attach (portal.es5.js:290)
    at OverlayRef.webpackJsonp.../../../cdk/esm5/overlay.es5.js.OverlayRef.attach (overlay.es5.js:655)
    at OwlDateTimeComponent.webpackJsonp.../../../../ng-pick-datetime/date-time/date-time-picker.component.js.OwlDateTimeComponent.openAsPopup (date-time-picker.component.js:294)
    at OwlDateTimeComponent.webpackJsonp.../../../../ng-pick-datetime/date-time/date-time-picker.component.js.OwlDateTimeComponent.open (date-time-picker.component.js:227)
    at OwlDateTimeTriggerDirective.webpackJsonp.../../../../ng-pick-datetime/date-time/date-time-picker-trigger.directive.js.OwlDateTimeTriggerDirective.handleClickOnHost (date-time-picker-trigger.directive.js:43)
    at Object.handleEvent (appointment-form.component.html:148)
    at handleEvent (core.js:13256)
    at callWithDebugContext (core.js:14741)
    at Object.debugHandleEvent [as handleEvent] (core.js:14328)

I think I found the issue and it seems to be with a variable called '_backdropElement'.  It's null in our dev environment, but has a value in local environment where the plugin works.  I did a console.log outputting 'this.popupRef' on line 294 of [date-time-picker.component.js.].

See this: [console output](http://72.3.144.28/images/error-image/CalendarBug.jpg)

**Update**
I'm building dev deployment using AOT.  When I build app for dev without AOT, then plugin works in our dev environment.  So, this issue is associated with AOT build process.

Please let me know if you need more information

**Comment by VlnRbn** [comment] 2018-02-22 11:45
Having same issue here

`ERROR Error: Attempting to attach an unknown Portal type. BasePortalOutlet accepts either a ComponentPortal or a TemplatePortal.`

Kindly fix this as soon as possible

**Comment by DanielYKPan** [comment] 2018-02-22 12:20
Could not reproduce the issue. 
Are you guys using angular cli to build your project?

**Comment by VlnRbn** [comment] 2018-02-22 12:46
Yes, @DanielYKPan , I'm Using angular CLI

**Comment by DanielYKPan** [comment] 2018-02-22 12:50
R u running the
```
ng build --prod
```
and caused the issue?

Please share your cdk version

**Comment by VlnRbn** [comment] 2018-02-22 12:52
"@angular/animations": "^5.1.1",
    "@angular/cdk": "^5.2.2",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",

**Comment by DanielYKPan** [comment] 2018-02-22 12:53
How do run into this issue?
Because I could not reproduce the issue in my cli apps

**Comment by VlnRbn** [comment] 2018-02-22 13:06
I use angular material in my project

**Comment by DanielYKPan** [comment] 2018-02-22 13:11
No, I am not asking this.

I am asking how you get this issue.

Because my demo page in github works fine. My demo page is using cli and built by
```
ng build --prod
```

**Comment by VlnRbn** [comment] 2018-02-22 15:42
I create a dummy project and build it, Its working. But in the main project its not working. Anyways thanks. @DanielYKPan .

**Comment by DanielYKPan** [comment] 2018-02-22 20:30
I guess it is not the issue from the picker.
I would close this for now.

**Comment by tomschreck** [comment] 2018-02-22 21:26
What’s the fix?

Sent from my iPhone

On Feb 22, 2018, at 12:30 PM, Yaokun Pan <notifications@github.com<mailto:notifications@github.com>> wrote:


I guess it is not the issue from the picker.
I would close this for now.

**Comment by DanielYKPan** [comment] 2018-02-22 21:40
@tomschreck 
Can you reproduce the issue from a dummy cli project?

**Comment by DanielYKPan** [comment] 2018-02-23 11:27
@tomschreck 
I have updated a new version.
Please use the picker version 5.1.7 and angular cdk 5.2.2, and see if the issue is solved.
Please let me know.
Thanks.

**Comment by tomschreck** [comment] 2018-02-23 15:08
Will do, thank you

Sent from my iPhone

On Feb 23, 2018, at 3:27 AM, Yaokun Pan <notifications@github.com<mailto:notifications@github.com>> wrote:


@tomschreck<https://github.com/tomschreck>
I have updated a new version.
Please use the picker version 5.1.7 and angular cdk 5.2.2, and see if the issue is solved.
Please let me know.
Thanks.

**Comment by AlixDaLegend** [comment] 2018-02-23 17:24
Hi,
I am currently facing the same problem.  As suggested, I've tried to use the material datepicker instead, and it worked well.  
I Will update the picker version to 5.1.7 and give you a feedback as well.
Thank you again for actions (and this great date/time picker module - suits my needs perfectly !!)

**Comment by DanielYKPan** [comment] 2018-02-23 23:09
The problem is I could not reproduce the issue, so it is difficult to debug the issue.

As I said before, I used angular cli to build the demo page. I run `ng build --prod ` to build the page, which is AOT. And I uploaded it to the server, and it works well.

@AlixDaLegend 
Could you tell me how you built your apps, like are you using the angular cli? are you built with AOT?

**Comment by VlnRbn** [comment] 2018-02-26 06:04
@DanielYKPan The issue fixed after updating to 5.1.7. Thanks for fix.

**Comment by DanielYKPan** [comment] 2018-02-26 07:58
Glad to hear that.

**Comment by AlixDaLegend** [comment] 2018-02-27 07:25
Hi.  The new version is working fine on my side as well.  Thank you very much :)

**Comment by DanielYKPan** [comment] 2018-02-27 08:14
Glad to hear that.

**Closed by DanielYKPan** 2018-02-27 08:14 UTC

**Comment by tomschreck** [comment] 2018-02-27 19:24
@DanielYKPan - thank you for the fix.  I updated to picker version 5.1.7 and angular cdk 5.2.3 and that fixed the problem.  Have a great day.

**Comment by ibadnabihashmi** [comment] 2018-03-07 04:34
Hey, i'm getting this error when serving app with `ng serve --prod` the app loads but when i click on the input this error appears, here is my package.json
` "dependencies": {`
   ` "@angular/animations": "^5.1.0",`
   ` "@angular/cdk": "5.2.4",`
    `"@angular/common": "^5.0.0",`
   ` "@angular/compiler": "^5.0.0",`
   ` "@angular/core": "^5.0.0",`
    `"@angular/flex-layout": "2.0.0-beta.10-4905443",`
    `"@angular/forms": "^5.0.0",`
   ` "@angular/http": "^5.0.0",`
  `  "@angular/material": "5.2.4",`
    `"@angular/platform-browser": "^5.0.0",`
  `  "@angular/platform-browser-dynamic": "^5.0.0",`
   ` "@angular/router": "^5.0.0",`
    `"@ngrx/effects": "^4.1.1",`
    `"@ngrx/router-store": "^4.1.1",`
    `"@ngrx/store": "^4.1.1",`
    `"core-js": "^2.4.1",`
   ` "hammerjs": "^2.0.8",`
   ` "ng-http-loader": "^0.6.0",`
   ` "ng-pick-datetime": "^5.1.7",`
   ` "ng-socket-io": "^0.2.4",`
   ` "ng-trim-value-accessor": "^2.0.2",`
    `"ngx-infinite-scroll": "^0.8.3",`
   ` "ngx-uploader": "^4.2.2",`
    `"rxjs": "^5.5.2",`
    `"zone.js": "^0.8.14"`
 ` }`

**Comment by ibadnabihashmi** [comment] 2018-03-07 06:15
@DanielYKPan , i think `@angular/material` is messing up, i actually updated angular material's cdk version too, but it didnt work.

**Comment by ibadnabihashmi** [comment] 2018-03-07 09:19
@DanielYKPan , it's fixed, pulled version 5.1.8.

**Comment by logicalravii** [comment] 2018-05-01 08:46
I have the same issue of  "ERROR Error: Attempting to attach an unknown Portal type. BasePortalOutlet accepts either a ComponentPortal or a TemplatePortal." and it is for me because i didn't use 
<label> outside of component . So please add <label> may be it could also be your problem. e.g.
<label>
    <owl-date-time ....>
</label>

**Comment by ratiuandreea** [comment] 2018-12-21 08:55
Is anyone facing issues in IE11 with ng serve --prod? 
In Chrome both ng serve and ng serve --prod commands work fine. But in IE11 I cannot select any dates when I use a production build version.

**Comment by ajju1090** [comment] 2019-05-07 10:13
I have still this issue @DanielYKPan .
I am using angular
"@angular/cdk": "^5.0.4",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.2.0",
    "@angular/fire": "^5.1.1",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/material": "^5.0.4",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/platform-server": "^4.0.1",
    "@angular/router": "^5.0.0",


Please help me.
![err](https://user-images.githubusercontent.com/8086848/57292214-e34c7480-70de-11e9-99a1-4d418eb0f0a3.png)
