### ISSUE TITLE
Ionic: Time input focus is overlapped by keyboard 

### ISSUE THREAD

**Issue by shyamal890** [DanielYKPan/date-time-picker#316] opened 2018-03-27 05:48 UTC
Ionic with `ion-input` the keyboard wouldn't overlap the time picker.

**Comment by DanielYKPan** [comment] 2018-03-27 06:25
Please use [StackBlitz](https://stackblitz.com/) to show the issue.

I would close this until there is a demo to show the issue.

**Closed by DanielYKPan** 2018-03-27 06:25 UTC

**Comment by shyamal890** [comment] 2018-03-29 06:54
![test](https://user-images.githubusercontent.com/6606965/38074308-f812a83e-334b-11e8-8dee-2b3ef1b2a3c1.gif)

Stackblitz link: https://stackblitz.com/edit/ionic-date-time-picker

Please select mobile phone as device from chrome debugging screen.

**Comment by DanielYKPan** [comment] 2018-03-29 07:17
This is not a bug. Your are using the picker as a inline element. If you replace the picker with any html element, that element would be out of the your screen too. 

If you are using the picker in mobile device, I would recommend set the picker as 'dialog' mode.  `<owl-date-time [pickerMode]=" 'dialog' "></owl-date-time>`

If you want to learn more about `[pickerMode]=" 'dialog' "`, you could find a example on the demo page and the description on the README.

**Comment by shyamal890** [comment] 2018-03-29 08:59
The point is even if you utilize the datepicker  in `dialog` mode, when you click on the time input the keyboard would overlap the time picker input. 

What I demonstrated in the input is that `ion-input` shifts the input just above the keyboard so that it is not hidden by the keyboard. This is not the case with the timepicker input field.
